{application,comeonin,
             [{registered,[]},
              {description,"Password hashing (bcrypt, pbkdf2_sha512) library for Elixir.\n"},
              {applications,[kernel,stdlib,elixir,crypto,logger]},
              {vsn,"2.0.0"},
              {modules,['Elixir.Comeonin','Elixir.Comeonin.Bcrypt',
                        'Elixir.Comeonin.Bcrypt.Base64',
                        'Elixir.Comeonin.Config','Elixir.Comeonin.Pbkdf2',
                        'Elixir.Comeonin.Pbkdf2.Base64',
                        'Elixir.Comeonin.Tools']}]}.